// GENERATED by tools/gen_params.py from protocol/params.json - do not edit.
#pragma once
#include <stdint.h>

namespace dd {

enum IconId : uint8_t {
  ICON_NONE = 0,
  ICON_TEMPERATURE = 1,
  ICON_TINT = 2,
  ICON_EXPOSURE = 3,
  ICON_CONTRAST = 4,
  ICON_HIGHLIGHTS = 5,
  ICON_SHADOWS = 6,
  ICON_WHITES = 7,
  ICON_BLACKS = 8,
  ICON_TEXTURE = 9,
  ICON_CLARITY = 10,
  ICON_DEHAZE = 11,
  ICON_VIBRANCE = 12,
  ICON_SATURATION = 13,
  ICON_SHARPNESS = 14,
  ICON_LUMINANCESMOOTHING = 15,
  ICON_POSTCROPVIGNETTEAMOUNT = 16,
  ICON_GRAINAMOUNT = 17,
  ICON_PARAMETRICHIGHLIGHTS = 18,
  ICON_PARAMETRICLIGHTS = 19,
  ICON_PARAMETRICDARKS = 20,
  ICON_PARAMETRICSHADOWS = 21,
  ICON_HUEADJUSTMENT = 22,
  ICON_SATURATIONADJUSTMENT = 23,
  ICON_LUMINANCEADJUSTMENT = 24,
  ICON_STATUS_OFFLINE = 25,
  ICON_STATUS_NOPHOTO = 26,
  ICON_STATUS_LOADED = 27,
  ICON_STATUS_DEVELOP = 28,
  ICON_TIMER_STOPWATCH = 29,
  ICON_TIMER_PLUS = 30,
  ICON_TIMER_STOP = 31,
  ICON_TIMER_CLIENT = 32,
  ICON_TIMER_BACK = 33,
  ICON_TIMER_CLOSE = 34,
  ICON_COUNT = 35
};

struct StatusText {
  uint8_t icon;
  const char *de;
  const char *en;
};

static const StatusText kStatusText[] = {
  {25, "Getrennt", "Offline"},  // offline
  {26, "Kein Foto", "No photo"},  // noPhoto
  {27, "Geladen", "Loaded"},  // loaded
  {28, "Entwickeln", "Develop"},  // develop
};

// Texts of the time tracking menu, indexed by TimerTextId.
enum TimerTextId : uint8_t {
  TEXT_STOP,
  TEXT_NEWJOB,
  TEXT_STARTED,
  TEXT_STOPPED,
  TEXT_TITLE,
  TEXT_CLIENTS,
  TEXT_CLIENT,
  TEXT_NEWCLIENT,
  TEXT_BACK,
  TEXT_CLOSE,
};

struct TimerText {
  const char *de;
  const char *en;
};

static const TimerText kTimerText[] = {
  {"Stopp", "Stop"},  // stop
  {"Neuer Job", "New job"},  // newJob
  {"Gestartet", "Started"},  // started
  {"Gestoppt", "Stopped"},  // stopped
  {"Zeiterfassung", "Time tracking"},  // title
  {"Kunden", "Clients"},  // clients
  {"Kunde", "Client"},  // client
  {"Neuer Kunde", "New client"},  // newClient
  {"Zur\303\274ck", "Back"},  // back
  {"Schlie\303\237en", "Close"},  // close
};

// Slots shown before the service has ever sent a configuration.
struct DefaultSlot {
  uint8_t paramId;
  uint8_t iconId;
  bool bipolar;
  const char *label;
};

static const uint8_t kDefaultSlotCount = 13;
static const DefaultSlot kDefaultSlots[] = {
  {1, 1, true, "Temp"},  // Temperature
  {2, 2, true, "Tint"},  // Tint
  {3, 3, true, "Exposure"},  // Exposure
  {4, 4, true, "Contrast"},  // Contrast
  {5, 5, true, "Highlights"},  // Highlights
  {6, 6, true, "Shadows"},  // Shadows
  {7, 7, true, "Whites"},  // Whites
  {8, 8, true, "Blacks"},  // Blacks
  {9, 9, true, "Texture"},  // Texture
  {10, 10, true, "Clarity"},  // Clarity
  {11, 11, true, "Dehaze"},  // Dehaze
  {12, 12, true, "Vibrance"},  // Vibrance
  {13, 13, true, "Saturation"},  // Saturation
};

}  // namespace dd
