#!/usr/bin/env python3
"""Turn the source graphics into what app and firmware need.

    tools/.venv/bin/python tools/gen_icons.py

Reads assets/icons/manifest.json and writes

  app/assets/icons/icon_NN.png           slider and status icons for the app
  app/assets/logo.png                    logo for the app
  app/assets/powered_by.png              "powered by" logo for the app
  app/assets/tray/*.png                  menu-bar icons (template images)
  app/macos/Runner/Assets.xcassets/...   macOS app icon
  firmware/darkdial/src/icons.c / .h     the same icons and the boot logo as
                                         LVGL images (RGB565)

Needs Pillow:  python3 -m venv tools/.venv && tools/.venv/bin/pip install pillow
"""
import json
import math
from pathlib import Path

from PIL import Image, ImageChops, ImageDraw

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "assets" / "icons" / "manifest.json"
APP_ASSETS = ROOT / "app" / "assets"
APP_ICONSET = ROOT / "app" / "macos" / "Runner" / "Assets.xcassets" / "AppIcon.appiconset"
FIRMWARE_SRC = ROOT / "firmware" / "darkdial" / "src"

APP_ICON_SIZE = 144
DEVICE_ICON_SIZE = 112
DISPLAY_SIZE = 360
POWERED_BY_SIZE = 176  # a square that fits the round display below the text
TRAY_SIZE = 36  # 18 pt @2x
HEADER = "GENERATED by tools/gen_icons.py - do not edit."


def circle_mask(size, radius, feather):
    """L mask: 255 inside `radius`, fading to 0 over `feather` pixels."""
    scale = 4
    big = Image.new("L", (size * scale, size * scale), 0)
    c = size * scale / 2
    r = radius * scale
    ImageDraw.Draw(big).ellipse((c - r, c - r, c + r, c + r), fill=255)
    mask = big.resize((size, size), Image.LANCZOS)
    if feather:
        from PIL import ImageFilter
        mask = mask.filter(ImageFilter.GaussianBlur(feather))
    return mask


def extract_symbol(path, crop, black_level):
    """Cuts the symbol out of a source image with baked-in bezel: centre crop,
    the dark disc pushed to pure black, edge faded out."""
    image = Image.open(path).convert("RGB")
    w, h = image.size
    left, top = (w - crop) // 2, (h - crop) // 2
    image = image.crop((left, top, left + crop, top + crop))
    # Black level: subtract by brightness so colours keep their hue.
    scale = 255.0 / (255 - black_level)
    pixels = image.load()
    for y in range(crop):
        for x in range(crop):
            r, g, b = pixels[x, y]
            m = max(r, g, b)
            if m <= black_level:
                pixels[x, y] = (0, 0, 0)
            else:
                f = (m - black_level) * scale / m
                pixels[x, y] = (min(255, round(r * f)), min(255, round(g * f)), min(255, round(b * f)))
    mask = circle_mask(crop, crop / 2 - 3, 1.5)
    black = Image.new("RGB", (crop, crop), (0, 0, 0))
    return Image.composite(image, black, mask), (left, top)


def draw_status(icon_id, size):
    """Placeholder status and time tracking icons, white line art in the style
    of the set."""
    s = 4
    n = size * s
    image = Image.new("RGB", (n, n), (0, 0, 0))
    d = ImageDraw.Draw(image)
    white = (255, 255, 255)
    stroke = round(n * 0.035)
    c = n / 2
    if icon_id == 25:  # offline: plug pulled apart
        r = n * 0.26
        d.arc((c - r, c - r, c + r, c + r), 200, 340, fill=white, width=stroke)
        d.arc((c - r, c - r, c + r, c + r), 20, 160, fill=white, width=stroke)
        d.line((c - n * 0.30, c + n * 0.30, c + n * 0.30, c - n * 0.30), fill=white, width=stroke)
    elif icon_id == 26:  # no photo: empty frame with slash
        d.rounded_rectangle((c - n * 0.30, c - n * 0.22, c + n * 0.30, c + n * 0.22),
                            radius=n * 0.04, outline=white, width=stroke)
        d.line((c - n * 0.33, c + n * 0.31, c + n * 0.33, c - n * 0.31), fill=white, width=stroke)
    elif icon_id == 27:  # loaded: check mark in a circle
        r = n * 0.30
        d.ellipse((c - r, c - r, c + r, c + r), outline=white, width=stroke)
        d.line((c - n * 0.14, c + n * 0.01, c - n * 0.03, c + n * 0.12, c + n * 0.16, c - n * 0.11),
               fill=white, width=stroke, joint="curve")
    elif icon_id == 28:  # develop: three sliders
        for i, knob in enumerate((0.25, -0.12, 0.10)):
            y = c + (i - 1) * n * 0.19
            d.line((c - n * 0.30, y, c + n * 0.30, y), fill=white, width=stroke)
            kx = c + knob * n
            kr = n * 0.055
            d.ellipse((kx - kr, y - kr, kx + kr, y + kr), fill=(0, 0, 0), outline=white, width=stroke)
    elif icon_id == 29:  # stopwatch
        r = n * 0.27
        cy = c + n * 0.04
        d.ellipse((c - r, cy - r, c + r, cy + r), outline=white, width=stroke)
        d.line((c, cy - r, c, cy - r - n * 0.07), fill=white, width=stroke)
        d.line((c - n * 0.07, cy - r - n * 0.07, c + n * 0.07, cy - r - n * 0.07), fill=white, width=stroke)
        d.line((c, cy, c + n * 0.11, cy - n * 0.13), fill=white, width=stroke)
    elif icon_id == 30:  # plus: new job
        a = n * 0.24
        d.line((c - a, c, c + a, c), fill=white, width=stroke)
        d.line((c, c - a, c, c + a), fill=white, width=stroke)
    elif icon_id == 31:  # stop
        a = n * 0.20
        d.rounded_rectangle((c - a, c - a, c + a, c + a), radius=n * 0.04, outline=white, width=stroke)
    return image.resize((size, size), Image.LANCZOS)


def rgb565_words(image):
    data = image.convert("RGB").tobytes()
    return [((data[i] >> 3) << 11) | ((data[i + 1] >> 2) << 5) | (data[i + 2] >> 3)
            for i in range(0, len(data), 3)]


def c_image(name, image):
    w, h = image.size
    words = rgb565_words(image)
    lines = [f"static const uint16_t {name}_map[{len(words)}] = {{"]
    for i in range(0, len(words), 16):
        lines.append("  " + ",".join(f"0x{v:04x}" for v in words[i:i + 16]) + ",")
    lines += [
        "};",
        f"const lv_image_dsc_t {name} = {{",
        "  .header = {",
        "    .magic = LV_IMAGE_HEADER_MAGIC,",
        "    .cf = LV_COLOR_FORMAT_RGB565,",
        f"    .w = {w},",
        f"    .h = {h},",
        f"    .stride = {w * 2},",
        "  },",
        f"  .data_size = sizeof({name}_map),",
        f"  .data = (const uint8_t *){name}_map,",
        "};",
        "",
    ]
    return "\n".join(lines)


def logo_disc(path):
    """The logo cropped to its disc, as a square RGB image."""
    image = Image.open(path).convert("RGB")
    bbox = image.point(lambda v: 255 if v > 40 else 0).getbbox()
    cx, cy = (bbox[0] + bbox[2]) / 2, (bbox[1] + bbox[3]) / 2
    half = max(bbox[2] - bbox[0], bbox[3] - bbox[1]) / 2
    return image.crop((round(cx - half), round(cy - half), round(cx + half), round(cy + half)))


def tray_icon(state):
    """Dial glyph as macOS template image: black with alpha."""
    s = 8
    n = TRAY_SIZE * s
    alpha = Image.new("L", (n, n), 0)
    d = ImageDraw.Draw(alpha)
    c = n / 2
    r = n * 0.40
    stroke = round(n * 0.085)
    level = 255 if state != "off" else 115
    # Ring with the gap at the bottom, like the value ring on the device.
    d.arc((c - r, c - r, c + r, c + r), 120, 60, fill=level, width=stroke)
    dot = n * 0.13
    if state == "ok":
        d.ellipse((c - dot, c - dot, c + dot, c + dot), fill=255)
    elif state == "partial":
        d.ellipse((c - dot, c - dot, c + dot, c + dot), outline=255, width=round(stroke * 0.7))
    alpha = alpha.resize((TRAY_SIZE, TRAY_SIZE), Image.LANCZOS)
    image = Image.new("RGBA", (TRAY_SIZE, TRAY_SIZE), (0, 0, 0, 0))
    image.putalpha(alpha)
    return image


def main():
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    source_dir = ROOT / manifest["sourceDir"]
    crop = manifest["crop"]

    (APP_ASSETS / "icons").mkdir(parents=True, exist_ok=True)
    (APP_ASSETS / "tray").mkdir(parents=True, exist_ok=True)

    c_parts = [f"// {HEADER}", '#include "icons.h"', ""]
    table = []
    crop_origin = (0, 0)
    for key in sorted(manifest["icons"], key=int):
        icon_id = int(key)
        source = manifest["icons"][key]
        if source:
            symbol, crop_origin = extract_symbol(source_dir / source, crop, manifest["blackLevel"])
        else:
            symbol = draw_status(icon_id, crop)
        symbol.resize((APP_ICON_SIZE, APP_ICON_SIZE), Image.LANCZOS).save(
            APP_ASSETS / "icons" / f"icon_{icon_id:02d}.png")
        name = f"dd_icon_{icon_id:02d}"
        c_parts.append(c_image(name, symbol.resize((DEVICE_ICON_SIZE, DEVICE_ICON_SIZE), Image.LANCZOS)))
        table.append((icon_id, name))

    disc = logo_disc(source_dir / manifest["logo"])
    c_parts.append(c_image("dd_logo", disc.resize((DISPLAY_SIZE, DISPLAY_SIZE), Image.LANCZOS)))

    # "powered by" logo: white artwork with alpha, on black for the device.
    powered = Image.open(source_dir / manifest["poweredByLogo"]).convert("RGBA")
    powered.resize((256, 256), Image.LANCZOS).save(APP_ASSETS / "powered_by.png")
    on_black = Image.new("RGBA", powered.size, (0, 0, 0, 255))
    on_black.alpha_composite(powered)
    c_parts.append(c_image("dd_powered_by", on_black.convert("RGB").resize(
        (POWERED_BY_SIZE, POWERED_BY_SIZE), Image.LANCZOS)))

    count = max(i for i, _ in table) + 1
    c_parts.append(f"const lv_image_dsc_t *const dd_icons[{count}] = {{")
    by_id = dict(table)
    for i in range(count):
        c_parts.append(f"  {'&' + by_id[i] if i in by_id else 'NULL'},")
    c_parts += ["};", ""]
    (FIRMWARE_SRC / "icons.c").write_text("\n".join(c_parts), encoding="utf-8")

    # Colour dot of the HSL icons, in icon pixels.
    dot = manifest["hslDot"]
    k = DEVICE_ICON_SIZE / crop
    dot_x = round((dot["x"] - crop_origin[0]) * k)
    dot_y = round((dot["y"] - crop_origin[1]) * k)
    dot_r = math.ceil(dot["radius"] * k)
    header = [
        f"// {HEADER}",
        "#pragma once",
        "#include <lvgl.h>",
        "",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
        "",
        f"#define DD_ICON_SIZE {DEVICE_ICON_SIZE}",
        f"#define DD_ICON_TABLE_SIZE {count}",
        "// Centre and radius of the colour dot inside the HSL icons.",
        f"#define DD_HSL_DOT_X {dot_x}",
        f"#define DD_HSL_DOT_Y {dot_y}",
        f"#define DD_HSL_DOT_R {dot_r}",
        "",
        "// Indexed by protocol icon ID; NULL where no icon exists.",
        f"extern const lv_image_dsc_t *const dd_icons[{count}];",
        "extern const lv_image_dsc_t dd_logo;",
        "extern const lv_image_dsc_t dd_powered_by;",
        "",
        "#ifdef __cplusplus",
        "}",
        "#endif",
        "",
    ]
    (FIRMWARE_SRC / "icons.h").write_text("\n".join(header), encoding="utf-8")

    # The same dot position for the app, relative to the icon size.
    (APP_ASSETS / "icons" / "hsl_dot.json").write_text(json.dumps({
        "x": (dot["x"] - crop_origin[0]) / crop,
        "y": (dot["y"] - crop_origin[1]) / crop,
        "radius": dot["radius"] / crop,
    }) + "\n", encoding="utf-8")

    # App logo and macOS icon: the disc on a transparent ground.
    disc_rgba = disc.resize((1024, 1024), Image.LANCZOS).convert("RGBA")
    disc_rgba.putalpha(circle_mask(1024, 510, 0))
    disc_rgba.resize((512, 512), Image.LANCZOS).save(APP_ASSETS / "logo.png")
    if APP_ICONSET.exists():
        # macOS icons keep a margin around the artwork.
        canvas = Image.new("RGBA", (1024, 1024), (0, 0, 0, 0))
        inner = disc_rgba.resize((880, 880), Image.LANCZOS)
        canvas.alpha_composite(inner, (72, 72))
        for size in (16, 32, 64, 128, 256, 512, 1024):
            canvas.resize((size, size), Image.LANCZOS).save(APP_ICONSET / f"app_icon_{size}.png")

    for state in ("ok", "partial", "off"):
        tray_icon(state).save(APP_ASSETS / "tray" / f"tray_{state}.png")

    print(f"{len(table)} icons, logo, tray icons written")


if __name__ == "__main__":
    main()
