#!/usr/bin/env python3
"""Generate the parameter tables for firmware and app from protocol/params.json.

    python3 tools/gen_params.py           write the generated files
    python3 tools/gen_params.py --check   exit 1 if a generated file is stale
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "protocol" / "params.json"
OUT_H = ROOT / "firmware" / "darkdial" / "src" / "core" / "params.h"
OUT_DART = ROOT / "app" / "packages" / "darkdial_core" / "lib" / "src" / "params.g.dart"

MAX_LABEL_CHARS = 10
HEADER = "GENERATED by tools/gen_params.py from protocol/params.json - do not edit."


def load():
    data = json.loads(SOURCE.read_text(encoding="utf-8"))
    params = [dict(p, color=None, colorDe=None, colorEn=None) for p in data["params"]]
    hsl = data["hsl"]
    for k, kind in enumerate(hsl["kinds"]):
        for c, color in enumerate(hsl["colors"]):
            params.append({
                "id": hsl["firstId"] + 8 * k + c,
                "lr": kind["lr"] + color["lr"],
                "group": hsl["group"],
                "de": kind["de"],
                "en": kind["en"],
                "ring": hsl["ring"],
                "icon": kind["icon"],
                "min": hsl["min"],
                "max": hsl["max"],
                "step": hsl["step"],
                "decimals": hsl["decimals"],
                "format": hsl["format"],
                "default": hsl["default"],
                "color": color["rgb"],
                "colorDe": color["de"],
                "colorEn": color["en"],
            })
    validate(params, data["status"], data["timerTexts"])
    return data, params


def validate(params, status, timer_texts):
    ids = [p["id"] for p in params]
    names = [p["lr"] for p in params]
    assert len(set(ids)) == len(ids), "duplicate parameter id"
    assert len(set(names)) == len(names), "duplicate Lightroom name"
    assert all(1 <= i <= 127 for i in ids), "parameter id out of range"
    for p in params:
        for lang in ("de", "en"):
            assert len(p[lang]) <= MAX_LABEL_CHARS, f"label too long: {p[lang]}"
        assert p["ring"] in ("bi", "uni")
        assert p["format"] in ("signed", "plain", "kelvin")
    for s in status:
        for lang in ("de", "en"):
            assert len(s[lang]) <= MAX_LABEL_CHARS, f"label too long: {s[lang]}"
    for t in timer_texts:
        for lang in ("de", "en"):
            # The help text is shown wrapped in the small font; everything else is one line.
            limit = 80 if t["key"] == "noClient" else 20
            assert len(t[lang].encode("utf-8")) <= limit, f"menu text too long: {t[lang]}"


def c_str(s):
    out = ""
    for b in s.encode("utf-8"):
        out += chr(b) if 0x20 <= b < 0x7F and chr(b) not in '"\\' else f"\\{b:03o}"
    return f'"{out}"'


def gen_h(data, params):
    icons = sorted({(p["icon"], p["lr"]) for p in params if p["color"] is None}
                   | {(k["icon"], k["lr"]) for k in data["hsl"]["kinds"]})
    lines = [
        f"// {HEADER}",
        "#pragma once",
        "#include <stdint.h>",
        "",
        "namespace dd {",
        "",
        "enum IconId : uint8_t {",
        "  ICON_NONE = 0,",
    ]
    for icon, name in icons:
        lines.append(f"  ICON_{name.upper()} = {icon},")
    for s in data["status"]:
        lines.append(f"  ICON_STATUS_{s['key'].upper()} = {s['icon']},")
    for t in data["timerIcons"]:
        lines.append(f"  ICON_TIMER_{t['key'].upper()} = {t['icon']},")
    last = max([i for i, _ in icons] + [s["icon"] for s in data["status"]] + [t["icon"] for t in data["timerIcons"]])
    lines += [f"  ICON_COUNT = {last + 1}", "};", ""]

    lines += [
        "struct StatusText {",
        "  uint8_t icon;",
        "  const char *de;",
        "  const char *en;",
        "};",
        "",
        "static const StatusText kStatusText[] = {",
    ]
    for s in data["status"]:
        lines.append(f"  {{{s['icon']}, {c_str(s['de'])}, {c_str(s['en'])}}},  // {s['key']}")
    lines += ["};", ""]

    lines += ["// Texts of the time tracking menu, indexed by TimerTextId.", "enum TimerTextId : uint8_t {"]
    for t in data["timerTexts"]:
        lines.append(f"  TEXT_{t['key'].upper()},")
    lines += ["};", "", "struct TimerText {", "  const char *de;", "  const char *en;", "};", "",
              "static const TimerText kTimerText[] = {"]
    for t in data["timerTexts"]:
        lines.append(f"  {{{c_str(t['de'])}, {c_str(t['en'])}}},  // {t['key']}")
    lines += ["};", ""]

    defaults = [p for p in params if p["default"]]
    lines += [
        "// Slots shown before the service has ever sent a configuration.",
        "struct DefaultSlot {",
        "  uint8_t paramId;",
        "  uint8_t iconId;",
        "  bool bipolar;",
        "  const char *label;",
        "};",
        "",
        f"static const uint8_t kDefaultSlotCount = {len(defaults)};",
        "static const DefaultSlot kDefaultSlots[] = {",
    ]
    for p in defaults:
        bipolar = "true" if p["ring"] == "bi" else "false"
        lines.append(f"  {{{p['id']}, {p['icon']}, {bipolar}, {c_str(p['en'])}}},  // {p['lr']}")
    lines += ["};", "", "}  // namespace dd", ""]
    return "\n".join(lines)


def dart_str(s):
    return "'" + s.replace("\\", "\\\\").replace("'", "\\'") + "'"


def dart_num(v):
    return repr(float(v))


def gen_dart(data, params):
    lines = [
        f"// {HEADER}",
        "// dart format off",
        "import 'param_def.dart';",
        "",
        "const List<ParamGroup> kParamGroups = [",
    ]
    for g in data["groups"]:
        lines.append(f"  ParamGroup({dart_str(g['key'])}, {dart_str(g['de'])}, {dart_str(g['en'])}),")
    lines += ["];", "", "const List<ParamDef> kParams = ["]
    for p in params:
        color = f"0x{p['color']}" if p["color"] else "null"
        fields = [
            f"id: {p['id']}",
            f"lr: {dart_str(p['lr'])}",
            f"group: {dart_str(p['group'])}",
            f"de: {dart_str(p['de'])}",
            f"en: {dart_str(p['en'])}",
            f"bipolar: {'true' if p['ring'] == 'bi' else 'false'}",
            f"icon: {p['icon']}",
            f"min: {dart_num(p['min'])}",
            f"max: {dart_num(p['max'])}",
            f"step: {dart_num(p['step'])}",
            f"decimals: {p['decimals']}",
            f"format: ValueFormat.{p['format']}",
            f"defaultActive: {'true' if p['default'] else 'false'}",
            f"color: {color}",
            f"colorDe: {dart_str(p['colorDe']) if p['colorDe'] else 'null'}",
            f"colorEn: {dart_str(p['colorEn']) if p['colorEn'] else 'null'}",
        ]
        lines.append("  ParamDef(" + ", ".join(fields) + "),")
    lines += ["];", "", "const List<StatusDef> kStatusDefs = ["]
    for s in data["status"]:
        lines.append(f"  StatusDef({dart_str(s['key'])}, {s['icon']}, {dart_str(s['de'])}, {dart_str(s['en'])}),")
    lines += ["];", "", "/// Icons of the time tracking menu by key.", "const Map<String, int> kTimerIcons = {"]
    for t in data["timerIcons"]:
        lines.append(f"  {dart_str(t['key'])}: {t['icon']},")
    lines += ["};", "", "/// Texts of the time tracking menu by key: [de, en].", "const Map<String, List<String>> kTimerTexts = {"]
    for t in data["timerTexts"]:
        lines.append(f"  {dart_str(t['key'])}: [{dart_str(t['de'])}, {dart_str(t['en'])}],")
    lines += ["};", ""]
    return "\n".join(lines)


def main():
    check = "--check" in sys.argv[1:]
    data, params = load()
    stale = []
    for path, text in ((OUT_H, gen_h(data, params)), (OUT_DART, gen_dart(data, params))):
        if check:
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                stale.append(path)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
            print(f"wrote {path.relative_to(ROOT)}")
    if stale:
        for path in stale:
            print(f"stale: {path.relative_to(ROOT)}", file=sys.stderr)
        sys.exit(1)
    if check:
        print(f"ok: {len(params)} parameters, generated files are in sync")


if __name__ == "__main__":
    main()
